//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmongUsToolbox.Windows.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AmongUsToolbox.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download a mod.
        /// </summary>
        public static string AddModButtonText {
            get {
                return ResourceManager.GetString("AddModButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add private server.
        /// </summary>
        public static string AddPrivateServerButtonText {
            get {
                return ResourceManager.GetString("AddPrivateServerButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add private server.
        /// </summary>
        public static string AddRegionButtonText {
            get {
                return ResourceManager.GetString("AddRegionButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add private server.
        /// </summary>
        public static string AddRegionTitle {
            get {
                return ResourceManager.GetString("AddRegionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Among Us game folder.
        /// </summary>
        public static string AmongUsFolderGroup {
            get {
                return ResourceManager.GetString("AmongUsFolderGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AppIcon {
            get {
                object obj = ResourceManager.GetObject("AppIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string ApplyModButtonText {
            get {
                return ResourceManager.GetString("ApplyModButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update private servers.
        /// </summary>
        public static string ApplyRegionsChangesText {
            get {
                return ResourceManager.GetString("ApplyRegionsChangesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Among Us Toolbox.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the color.
        /// </summary>
        public static string ChooseColorButton {
            get {
                return ResourceManager.GetString("ChooseColorButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompression in progress.
        /// </summary>
        public static string DecompressionInProgress {
            get {
                return ResourceManager.GetString("DecompressionInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Among Us Mods Manager don&apos;t have write access in {0}. Please select another folder or open the mods manager as administrator..
        /// </summary>
        public static string DirectoryNotWritableMessage {
            get {
                return ResourceManager.GetString("DirectoryNotWritableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory not writable.
        /// </summary>
        public static string DirectoryNotWritableTitle {
            get {
                return ResourceManager.GetString("DirectoryNotWritableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable SSL/TLS.
        /// </summary>
        public static string DisableSslLabel {
            get {
                return ResourceManager.GetString("DisableSslLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string DownloadModButton {
            get {
                return ResourceManager.GetString("DownloadModButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download a mod.
        /// </summary>
        public static string DownloadModTitle {
            get {
                return ResourceManager.GetString("DownloadModTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download status.
        /// </summary>
        public static string DownloadStatus {
            get {
                return ResourceManager.GetString("DownloadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap EditIcon {
            get {
                object obj = ResourceManager.GetObject("EditIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable debug mode (requires application restart).
        /// </summary>
        public static string EnableDebugMode {
            get {
                return ResourceManager.GetString("EnableDebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting.
        /// </summary>
        public static string Extracting {
            get {
                return ResourceManager.GetString("Extracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostname/IP address.
        /// </summary>
        public static string HostLabel {
            get {
                return ResourceManager.GetString("HostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to change mod because Among Us game is open..
        /// </summary>
        public static string InstallErrorGameRunning {
            get {
                return ResourceManager.GetString("InstallErrorGameRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation not permitted.
        /// </summary>
        public static string InstallErrorGameRunningTitle {
            get {
                return ResourceManager.GetString("InstallErrorGameRunningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to remove this mod because Among Us game is open..
        /// </summary>
        public static string ModDeletionErrorGameRunning {
            get {
                return ResourceManager.GetString("ModDeletionErrorGameRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation not permitted.
        /// </summary>
        public static string ModDeletionErrorGameRunningTitle {
            get {
                return ResourceManager.GetString("ModDeletionErrorGameRunningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ModIcon {
            get {
                object obj = ResourceManager.GetObject("ModIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage mods.
        /// </summary>
        public static string ModsTitle {
            get {
                return ResourceManager.GetString("ModsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse repository: {0}. Please use Github URL or owner/repository.
        /// </summary>
        public static string ParseRepositoryError {
            get {
                return ResourceManager.GetString("ParseRepositoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad repository format.
        /// </summary>
        public static string ParseRepositoryErrorTitle {
            get {
                return ResourceManager.GetString("ParseRepositoryErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private server name.
        /// </summary>
        public static string PrivateServerNameLabel {
            get {
                return ResourceManager.GetString("PrivateServerNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the {0} private server?.
        /// </summary>
        public static string RegionDeletionMessage {
            get {
                return ResourceManager.GetString("RegionDeletionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private server deletion.
        /// </summary>
        public static string RegionDeletionTitle {
            get {
                return ResourceManager.GetString("RegionDeletionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RegionIcon {
            get {
                object obj = ResourceManager.GetObject("RegionIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage private servers.
        /// </summary>
        public static string RegionsTitle {
            get {
                return ResourceManager.GetString("RegionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RemoveIcon {
            get {
                object obj = ResourceManager.GetObject("RemoveIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod repository.
        /// </summary>
        public static string RepoLabel {
            get {
                return ResourceManager.GetString("RepoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Among Us folder.
        /// </summary>
        public static string SelectAmongUsFolder {
            get {
                return ResourceManager.GetString("SelectAmongUsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your Among Us game folder.
        /// </summary>
        public static string SelectFolderLabel {
            get {
                return ResourceManager.GetString("SelectFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsButton {
            get {
                return ResourceManager.GetString("SettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SettingsIcon {
            get {
                object obj = ResourceManager.GetObject("SettingsIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the latest resource in the following repository:.
        /// </summary>
        public static string UnableToFindAsset {
            get {
                return ResourceManager.GetString("UnableToFindAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset not found.
        /// </summary>
        public static string UnableToFindAssetTitle {
            get {
                return ResourceManager.GetString("UnableToFindAssetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the following repository:.
        /// </summary>
        public static string UnableToFindRepository {
            get {
                return ResourceManager.GetString("UnableToFindRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository not found.
        /// </summary>
        public static string UnableToFindRepositoryTitle {
            get {
                return ResourceManager.GetString("UnableToFindRepositoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap UpdateIcon {
            get {
                object obj = ResourceManager.GetObject("UpdateIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update private server.
        /// </summary>
        public static string UpdateRegionButtonText {
            get {
                return ResourceManager.GetString("UpdateRegionButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update private server.
        /// </summary>
        public static string UpdateRegionTitle {
            get {
                return ResourceManager.GetString("UpdateRegionTitle", resourceCulture);
            }
        }
    }
}
